# Single source of truth for tests/test_country_code.py (a blocking CI
# check) and .github/workflows/ai-pr-review.py (the advisory AIOps check) —
# both need the same ISO 3166-1 alpha-2 -> country table and shouldn't
# maintain separate copies.
#
# This is a fallback only: used when an (alpha_two_code, country) pairing
# has no precedent elsewhere in world_universities_and_domains.json, so
# there's no existing usage in the dataset itself to check self-consistency
# against. Sets list the ISO 3166-1 English short name plus common accepted
# variants actually seen in this dataset, not every possible spelling.
ISO_3166_ALPHA2_COUNTRIES = {
    "AD": {"Andorra"},
    "AE": {"United Arab Emirates"},
    "AF": {"Afghanistan"},
    "AG": {"Antigua and Barbuda"},
    "AI": {"Anguilla"},
    "AL": {"Albania"},
    "AM": {"Armenia"},
    "AO": {"Angola"},
    "AQ": {"Antarctica"},
    "AR": {"Argentina"},
    "AS": {"American Samoa"},
    "AT": {"Austria"},
    "AU": {"Australia"},
    "AW": {"Aruba"},
    "AX": {"Åland Islands"},
    "AZ": {"Azerbaijan"},
    "BA": {"Bosnia and Herzegovina"},
    "BB": {"Barbados"},
    "BD": {"Bangladesh"},
    "BE": {"Belgium"},
    "BF": {"Burkina Faso"},
    "BG": {"Bulgaria"},
    "BH": {"Bahrain"},
    "BI": {"Burundi"},
    "BJ": {"Benin"},
    "BL": {"Saint Barthélemy"},
    "BM": {"Bermuda"},
    "BN": {"Brunei", "Brunei Darussalam"},
    "BO": {
        "Bolivia",
        "Plurinational State of Bolivia",
        "Bolivia, Plurinational State of",
    },
    "BQ": {"Bonaire, Sint Eustatius and Saba"},
    "BR": {"Brazil"},
    "BS": {"Bahamas"},
    "BT": {"Bhutan"},
    "BV": {"Bouvet Island"},
    "BW": {"Botswana"},
    "BY": {"Belarus"},
    "BZ": {"Belize"},
    "CA": {"Canada"},
    "CC": {"Cocos (Keeling) Islands"},
    "CD": {
        "Democratic Republic of the Congo",
        "DR Congo",
        "Congo, the Democratic Republic of the",
    },
    "CF": {"Central African Republic"},
    "CG": {"Congo", "Republic of the Congo"},
    "CH": {"Switzerland"},
    "CI": {"Côte d'Ivoire", "Ivory Coast", "Cote d'Ivoire"},
    "CK": {"Cook Islands"},
    "CL": {"Chile"},
    "CM": {"Cameroon"},
    "CN": {"China"},
    "CO": {"Colombia"},
    "CR": {"Costa Rica"},
    "CU": {"Cuba"},
    "CV": {"Cabo Verde", "Cape Verde"},
    "CW": {"Curaçao"},
    "CX": {"Christmas Island"},
    "CY": {"Cyprus"},
    "CZ": {"Czech Republic", "Czechia"},
    "DE": {"Germany"},
    "DJ": {"Djibouti"},
    "DK": {"Denmark"},
    "DM": {"Dominica"},
    "DO": {"Dominican Republic"},
    "DZ": {"Algeria"},
    "EC": {"Ecuador"},
    "EE": {"Estonia"},
    "EG": {"Egypt"},
    "EH": {"Western Sahara"},
    "ER": {"Eritrea"},
    "ES": {"Spain"},
    "ET": {"Ethiopia"},
    "FI": {"Finland"},
    "FJ": {"Fiji"},
    "FK": {"Falkland Islands"},
    "FM": {"Micronesia", "Federated States of Micronesia"},
    "FO": {"Faroe Islands"},
    "FR": {"France"},
    "GA": {"Gabon"},
    "GB": {"United Kingdom"},
    "GD": {"Grenada"},
    "GE": {"Georgia"},
    "GF": {"French Guiana"},
    "GG": {"Guernsey"},
    "GH": {"Ghana"},
    "GI": {"Gibraltar"},
    "GL": {"Greenland"},
    "GM": {"Gambia"},
    "GN": {"Guinea"},
    "GP": {"Guadeloupe"},
    "GQ": {"Equatorial Guinea"},
    "GR": {"Greece"},
    "GS": {"South Georgia and the South Sandwich Islands"},
    "GT": {"Guatemala"},
    "GU": {"Guam"},
    "GW": {"Guinea-Bissau"},
    "GY": {"Guyana"},
    "HK": {"Hong Kong"},
    "HM": {"Heard Island and McDonald Islands"},
    "HN": {"Honduras"},
    "HR": {"Croatia"},
    "HT": {"Haiti"},
    "HU": {"Hungary"},
    "ID": {"Indonesia"},
    "IE": {"Ireland"},
    "IL": {"Israel"},
    "IM": {"Isle of Man"},
    "IN": {"India"},
    "IO": {"British Indian Ocean Territory"},
    "IQ": {"Iraq"},
    "IR": {"Iran", "Islamic Republic of Iran"},
    "IS": {"Iceland"},
    "IT": {"Italy"},
    "JE": {"Jersey"},
    "JM": {"Jamaica"},
    "JO": {"Jordan"},
    "JP": {"Japan"},
    "KE": {"Kenya"},
    "KG": {"Kyrgyzstan"},
    "KH": {"Cambodia"},
    "KI": {"Kiribati"},
    "KM": {"Comoros"},
    "KN": {"Saint Kitts and Nevis"},
    "KP": {
        "North Korea",
        "Democratic People's Republic of Korea",
        "Korea, Democratic People's Republic of",
    },
    "KR": {"South Korea", "Republic of Korea", "Korea, Republic of"},
    "KW": {"Kuwait"},
    "KY": {"Cayman Islands"},
    "KZ": {"Kazakhstan"},
    "LA": {"Laos", "Lao People's Democratic Republic"},
    "LB": {"Lebanon"},
    "LC": {"Saint Lucia"},
    "LI": {"Liechtenstein"},
    "LK": {"Sri Lanka"},
    "LR": {"Liberia"},
    "LS": {"Lesotho"},
    "LT": {"Lithuania"},
    "LU": {"Luxembourg"},
    "LV": {"Latvia"},
    "LY": {"Libya"},
    "MA": {"Morocco"},
    "MC": {"Monaco"},
    "MD": {"Moldova", "Republic of Moldova", "Moldova, Republic of"},
    "ME": {"Montenegro"},
    "MF": {"Saint Martin"},
    "MG": {"Madagascar"},
    "MH": {"Marshall Islands"},
    "MK": {"North Macedonia", "Macedonia"},
    "ML": {"Mali"},
    "MM": {"Myanmar", "Burma"},
    "MN": {"Mongolia"},
    "MO": {"Macao"},
    "MP": {"Northern Mariana Islands"},
    "MQ": {"Martinique"},
    "MR": {"Mauritania"},
    "MS": {"Montserrat"},
    "MT": {"Malta"},
    "MU": {"Mauritius"},
    "MV": {"Maldives"},
    "MW": {"Malawi"},
    "MX": {"Mexico"},
    "MY": {"Malaysia"},
    "MZ": {"Mozambique"},
    "NA": {"Namibia"},
    "NC": {"New Caledonia"},
    "NE": {"Niger"},
    "NF": {"Norfolk Island"},
    "NG": {"Nigeria"},
    "NI": {"Nicaragua"},
    "NL": {"Netherlands"},
    "NO": {"Norway"},
    "NP": {"Nepal"},
    "NR": {"Nauru"},
    "NU": {"Niue"},
    "NZ": {"New Zealand"},
    "OM": {"Oman"},
    "PA": {"Panama"},
    "PE": {"Peru"},
    "PF": {"French Polynesia"},
    "PG": {"Papua New Guinea"},
    "PH": {"Philippines"},
    "PK": {"Pakistan"},
    "PL": {"Poland"},
    "PM": {"Saint Pierre and Miquelon"},
    "PN": {"Pitcairn"},
    "PR": {"Puerto Rico"},
    "PS": {"Palestine", "State of Palestine", "Palestine, State of"},
    "PT": {"Portugal"},
    "PW": {"Palau"},
    "PY": {"Paraguay"},
    "QA": {"Qatar"},
    "RE": {"Réunion"},
    "RO": {"Romania"},
    "RS": {"Serbia"},
    "RU": {"Russia", "Russian Federation"},
    "RW": {"Rwanda"},
    "SA": {"Saudi Arabia"},
    "SB": {"Solomon Islands"},
    "SC": {"Seychelles"},
    "SD": {"Sudan"},
    "SE": {"Sweden"},
    "SG": {"Singapore"},
    "SH": {"Saint Helena, Ascension and Tristan da Cunha"},
    "SI": {"Slovenia"},
    "SJ": {"Svalbard and Jan Mayen"},
    "SK": {"Slovakia"},
    "SL": {"Sierra Leone"},
    "SM": {"San Marino"},
    "SN": {"Senegal"},
    "SO": {"Somalia"},
    "SR": {"Suriname"},
    "SS": {"South Sudan"},
    "ST": {"Sao Tome and Principe"},
    "SV": {"El Salvador"},
    "SX": {"Sint Maarten"},
    "SY": {"Syria", "Syrian Arab Republic"},
    "SZ": {"Eswatini", "Swaziland"},
    "TC": {"Turks and Caicos Islands"},
    "TD": {"Chad"},
    "TF": {"French Southern Territories"},
    "TG": {"Togo"},
    "TH": {"Thailand"},
    "TJ": {"Tajikistan"},
    "TK": {"Tokelau"},
    "TL": {"Timor-Leste", "East Timor"},
    "TM": {"Turkmenistan"},
    "TN": {"Tunisia"},
    "TO": {"Tonga"},
    "TR": {"Turkey", "Türkiye", "Turkiye"},
    "TT": {"Trinidad and Tobago"},
    "TV": {"Tuvalu"},
    "TW": {"Taiwan", "Taiwan, Province of China"},
    "TZ": {"Tanzania", "United Republic of Tanzania", "Tanzania, United Republic of"},
    "UA": {"Ukraine"},
    "UG": {"Uganda"},
    "UM": {"United States Minor Outlying Islands"},
    "US": {"United States", "United States of America"},
    "UY": {"Uruguay"},
    "UZ": {"Uzbekistan"},
    "VA": {"Vatican City", "Holy See", "Holy See (Vatican City State)"},
    "VC": {"Saint Vincent and the Grenadines"},
    "VE": {
        "Venezuela",
        "Bolivarian Republic of Venezuela",
        "Venezuela, Bolivarian Republic of",
    },
    "VG": {"British Virgin Islands", "Virgin Islands, British"},
    "VI": {"United States Virgin Islands"},
    "VN": {"Vietnam", "Viet Nam"},
    "VU": {"Vanuatu"},
    "WF": {"Wallis and Futuna"},
    "WS": {"Samoa"},
    "YE": {"Yemen"},
    "YT": {"Mayotte"},
    "ZA": {"South Africa"},
    "ZM": {"Zambia"},
    "ZW": {"Zimbabwe"},
    # Not an official ISO 3166-1 code, but a widely used user-assigned one
    # for Kosovo (already present in this dataset).
    "XK": {"Kosovo"},
}
