name: '🏫 New University Request'
description: Request to add a new university to the list.
labels: ['add-university', 'triage']
body:
  - type: input
    id: univ_name
    attributes:
      label: University Name
      placeholder: 'e.g., Istanbul Technical University'
    validations:
      required: true
  - type: input
    id: univ_website
    attributes:
      label: Website URL
      placeholder: 'e.g., http://www.itu.edu.tr/'
    validations:
      required: true
  - type: input
    id: univ_domain
    attributes:
      label: Domain(s)
      placeholder: 'e.g., itu.edu.tr (Separate by commas if multiple)'
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Country
      placeholder: 'e.g., Turkiye'
    validations:
      required: true
  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      options:
        - label: I have verified that this university is not already in the list.
          required: true
